In [24]:
import pandas as pd
import numpy as np

In [25]:
data=pd.read_csv('movie_metadata.csv')
data.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [26]:
data=data[['movie_title', 'title_year', 'genres', 'language', 'country','color',
           'director_name', 'actor_1_name', 'actor_2_name', 'actor_3_name']]
data.head()

,movie_title,title_year,genres,language,country,color,director_name,actor_1_name,actor_2_name,actor_3_name
0,Avatar,2009.0,Action|Adventure|Fantasy|Sci-Fi,English,USA,Color,James Cameron,CCH Pounder,Joel David Moore,Wes Studi
1,Pirates of the Caribbean: At World's End,2007.0,Action|Adventure|Fantasy,English,USA,Color,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport
2,Spectre,2015.0,Action|Adventure|Thriller,English,UK,Color,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman
3,The Dark Knight Rises,2012.0,Action|Thriller,English,USA,Color,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt
4,Star Wars: Episode VII - The Force AwakensÂ ...,NaN,Documentary,NaN,NaN,NaN,Doug Walker,Doug Walker,Rob Walker,NaN

In [27]:
data.isnull().sum()

movie_title        0
title_year       108
genres             0
language          12
country            5
color             19
director_name    104
actor_1_name       7
actor_2_name      13
actor_3_name      23
dtype: int64

In [28]:
data.duplicated(subset=['movie_title'])

0       False
1       False
2       False
3       False
4       False
        ...
5038    False
5039    False
5040    False
5041    False
5042    False
Length: 5043, dtype: bool

In [29]:
data_no_duplicates = data.drop_duplicates()
print((data.shape[0] - data_no_duplicates.shape[0]),' Perfect duplicates deleted.')
data = data_no_duplicates
data_no_duplicates = data.drop_duplicates(subset=['movie_title', 'title_year'])
print((data.shape[0] - data_no_duplicates.shape[0]),' duplicates by names')
data = data_no_duplicates

123  Perfect duplicates deleted.
1  duplicates by names

In [30]:
data['movie_title'] = data['movie_title'].str.strip()

In [31]:
data.head()

,movie_title,title_year,genres,language,country,color,director_name,actor_1_name,actor_2_name,actor_3_name
0,Avatar,2009.0,Action|Adventure|Fantasy|Sci-Fi,English,USA,Color,James Cameron,CCH Pounder,Joel David Moore,Wes Studi
1,Pirates of the Caribbean: At World's End,2007.0,Action|Adventure|Fantasy,English,USA,Color,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport
2,Spectre,2015.0,Action|Adventure|Thriller,English,UK,Color,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman
3,The Dark Knight Rises,2012.0,Action|Thriller,English,USA,Color,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt
4,Star Wars: Episode VII - The Force Awakens,NaN,Documentary,NaN,NaN,NaN,Doug Walker,Doug Walker,Rob Walker,NaN

In [32]:
data['title_year'].fillna( value=round(data.title_year.mean()) , inplace=True )
data['language'].fillna( value='English' , inplace=True )
data['country'].fillna( value='USA' , inplace=True )
data['color'].fillna( value='Color' , inplace=True )

for col in ['director_name', 'actor_1_name', 'actor_2_name', 'actor_3_name']:
    data[col].fillna( value='' , inplace=True )

data.head()

,movie_title,title_year,genres,language,country,color,director_name,actor_1_name,actor_2_name,actor_3_name
0,Avatar,2009.0,Action|Adventure|Fantasy|Sci-Fi,English,USA,Color,James Cameron,CCH Pounder,Joel David Moore,Wes Studi
1,Pirates of the Caribbean: At World's End,2007.0,Action|Adventure|Fantasy,English,USA,Color,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport
2,Spectre,2015.0,Action|Adventure|Thriller,English,UK,Color,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman
3,The Dark Knight Rises,2012.0,Action|Thriller,English,USA,Color,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt
4,Star Wars: Episode VII - The Force Awakens,2002.0,Documentary,English,USA,Color,Doug Walker,Doug Walker,Rob Walker,

In [33]:
data_words = data[['movie_title', 'genres', 'language','country', 'color', 'director_name', 'actor_1_name', 'actor_2_name', 'actor_3_name']]

def replace_space(val):
    val = val.str.replace(' ','_')
    val = val.str.replace('.','')
    return val

data_words = data_words.apply(replace_space, axis=1)
data_words.head()

C:\Users\Shadin\AppData\Local\Temp/ipykernel_8172/3222001142.py:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  val = val.str.replace('.','')

,movie_title,genres,language,country,color,director_name,actor_1_name,actor_2_name,actor_3_name
0,Avatar,Action|Adventure|Fantasy|Sci-Fi,English,USA,Color,James_Cameron,CCH_Pounder,Joel_David_Moore,Wes_Studi
1,Pirates_of_the_Caribbean:_At_World's_End,Action|Adventure|Fantasy,English,USA,Color,Gore_Verbinski,Johnny_Depp,Orlando_Bloom,Jack_Davenport
2,Spectre,Action|Adventure|Thriller,English,UK,Color,Sam_Mendes,Christoph_Waltz,Rory_Kinnear,Stephanie_Sigman
3,The_Dark_Knight_Rises,Action|Thriller,English,USA,Color,Christopher_Nolan,Tom_Hardy,Christian_Bale,Joseph_Gordon-Levitt
4,Star_Wars:_Episode_VII_-_The_Force_Awakens,Documentary,English,USA,Color,Doug_Walker,Doug_Walker,Rob_Walker,

In [35]:
data['words'] = (data_words['movie_title'] +
               ' ' + data_words['genres'].str.replace('|', ' ') +
               ' ' + data_words['language'] +
               ' ' + data_words['country'] +
               ' ' + data_words['color'] +
               ' ' + data_words['director_name'] +
               ' ' + data_words['actor_1_name'] +
               ' ' + data_words['actor_2_name'] +
               ' ' + data_words['actor_3_name']
              )
data.head()

C:\Users\Shadin\AppData\Local\Temp/ipykernel_8172/2087992050.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  ' ' + data_words['genres'].str.replace('|', ' ') +

,movie_title,title_year,genres,language,country,color,director_name,actor_1_name,actor_2_name,actor_3_name,words
0,Avatar,2009.0,Action|Adventure|Fantasy|Sci-Fi,English,USA,Color,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Avatar Action Adventure Fantasy Sci-Fi English...
1,Pirates of the Caribbean: At World's End,2007.0,Action|Adventure|Fantasy,English,USA,Color,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Pirates_of_the_Caribbean:_At_World's_End Actio...
2,Spectre,2015.0,Action|Adventure|Thriller,English,UK,Color,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Spectre Action Adventure Thriller English UK C...
3,The Dark Knight Rises,2012.0,Action|Thriller,English,USA,Color,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,The_Dark_Knight_Rises Action Thriller English ...
4,Star Wars: Episode VII - The Force Awakens,2002.0,Documentary,English,USA,Color,Doug Walker,Doug Walker,Rob Walker,,Star_Wars:_Episode_VII_-_The_Force_Awakens Doc...

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(data['words'])
tfidf_matrix.shape

(4919, 14258)

In [37]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(stop_words='english')
cv_matrix = cv.fit_transform(data['words'])
cv_matrix.shape

(4919, 14258)

In [38]:
from sklearn.metrics.pairwise import linear_kernel

cosine_sim_tfidf = linear_kernel(tfidf_matrix, tfidf_matrix)
cosine_sim_cv = linear_kernel(cv_matrix, cv_matrix)

In [39]:
indices = pd.Series(data.index, index=data['movie_title'])

In [40]:
def get_recommendations(title, cosine_sim):
    idx = indices[title]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:11]
    movie_indices = [i[0] for i in sim_scores]
    return data['movie_title'].iloc[movie_indices]

In [41]:
get_recommendations('The Avengers', cosine_sim_tfidf)

8                   Avengers: Age of Ultron
80                               Iron Man 2
27               Captain America: Civil War
1334                               Serenity
160                               Star Trek
280                              The Island
32                               Iron Man 3
69                                 Iron Man
86      Captain America: The Winter Soldier
130                                    Thor
Name: movie_title, dtype: object

In [42]:
get_recommendations('The Avengers', cosine_sim_cv)

8                   Avengers: Age of Ultron
27               Captain America: Civil War
80                               Iron Man 2
32                               Iron Man 3
69                                 Iron Man
86      Captain America: The Winter Soldier
160                               Star Trek
280                              The Island
1334                               Serenity
0                                    Avatar
Name: movie_title, dtype: object